// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// APIErrorNotFound - Not Found error
type APIErrorNotFound struct {
	Status   int                     `json:"status"`
	Error_   string                  `json:"error"`
	Code     string                  `json:"code"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &APIErrorNotFound{}

func (e *APIErrorNotFound) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
