// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// APIErrorUnauthorized - Unauthorized error
type APIErrorUnauthorized struct {
	Status   int                     `json:"status"`
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &APIErrorUnauthorized{}

func (e *APIErrorUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
