/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petDeletePet } from "../../funcs/petDeletePet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeletePetRequest$inboundSchema,
};

export const tool$petDeletePet: ToolDefinition<typeof args> = {
  name: "pet-delete-pet",
  description: `Deletes a pet`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petDeletePet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
