/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petFindPetsByStatusTypes } from "../../funcs/petFindPetsByStatusTypes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FindPetsByStatusTypesRequest$inboundSchema,
};

export const tool$petFindPetsByStatusTypes: ToolDefinition<typeof args> = {
  name: "pet-find-pets-by-status-types",
  description: `Finds Pets by status

Multiple status values can be provided with comma separated strings`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petFindPetsByStatusTypes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
