/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petPetsStoreMonday } from "../../funcs/petPetsStoreMonday.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.Pet$inboundSchema,
};

export const tool$petPetsStoreMonday: ToolDefinition<typeof args> = {
  name: "pet-pets-store-monday",
  description: `Update an existing pet

Update an existing pet by Id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petPetsStoreMonday(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
