/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storeGetOrderById } from "../../funcs/storeGetOrderById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrderByIdRequest$inboundSchema,
};

export const tool$storeGetOrderById: ToolDefinition<typeof args> = {
  name: "store-get-order-by-id",
  description: `Find purchase order by ID

For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await storeGetOrderById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
