/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userSayNewRandom } from "../../funcs/userSayNewRandom.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$userSayNewRandom: ToolDefinition = {
  name: "user-say-new-random",
  description: `Say new random

Returns a new random message`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await userSayNewRandom(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
