/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userSayRandom } from "../../funcs/userSayRandom.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$userSayRandom: ToolDefinition = {
  name: "user-say-random",
  description: `Say random

Returns a random message`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await userSayRandom(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
