/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userLoginUser } from "../../funcs/userLoginUser.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LoginUserRequest$inboundSchema,
};

export const tool$userLoginUser: ToolDefinition<typeof args> = {
  name: "user-login-user",
  description: `Logs user into the system`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userLoginUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
