/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userSayHello } from "../../funcs/userSayHello.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$userSayHello: ToolDefinition = {
  name: "user-say-hello",
  description: `Say hello

Returns a simple hello message`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await userSayHello(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
