/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { userCreateUsersWithListInput } from "../../funcs/userCreateUsersWithListInput.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(components.User$inboundSchema).optional(),
};

export const tool$userCreateUsersWithListInput: ToolDefinition<typeof args> = {
  name: "user-create-users-with-list-input",
  description: `Creates list of users with given input array

Creates list of users with given input array`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userCreateUsersWithListInput(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
