/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { PetstoreCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$petDeletePet } from "./tools/petDeletePet.js";
import { tool$petFindPetsByStatusTypes } from "./tools/petFindPetsByStatusTypes.js";
import { tool$petFindPetsByTags } from "./tools/petFindPetsByTags.js";
import { tool$petGetPetByIDS } from "./tools/petGetPetByIDS.js";
import { tool$petMCPTest } from "./tools/petMCPTest.js";
import { tool$petPetsStoreMonday } from "./tools/petPetsStoreMonday.js";
import { tool$petUploadFile } from "./tools/petUploadFile.js";
import { tool$storeDeleteOrder } from "./tools/storeDeleteOrder.js";
import { tool$storeGetInventory } from "./tools/storeGetInventory.js";
import { tool$storeGetOrderById } from "./tools/storeGetOrderById.js";
import { tool$storePlaceOrder } from "./tools/storePlaceOrder.js";
import { tool$userCreateUser } from "./tools/userCreateUser.js";
import { tool$userCreateUsersWithListInput } from "./tools/userCreateUsersWithListInput.js";
import { tool$userDeleteUser } from "./tools/userDeleteUser.js";
import { tool$userGetUserByName } from "./tools/userGetUserByName.js";
import { tool$userLoginUser } from "./tools/userLoginUser.js";
import { tool$userLogoutUser } from "./tools/userLogoutUser.js";
import { tool$userSayRandom } from "./tools/userSayRandom.js";
import { tool$userUpdateUser } from "./tools/userUpdateUser.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKey?: SDKOptions["apiKey"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  environment?: SDKOptions["environment"] | undefined;
}) {
  const server = new McpServer({
    name: "Petstore",
    version: "5.2.0-alpha.37",
  });

  const client = new PetstoreCore({
    apiKey: deps.apiKey,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
    environment: deps.environment,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$petPetsStoreMonday);
  tool(tool$petMCPTest);
  tool(tool$petFindPetsByStatusTypes);
  tool(tool$petFindPetsByTags);
  tool(tool$petGetPetByIDS);
  tool(tool$petDeletePet);
  tool(tool$petUploadFile);
  tool(tool$storeGetInventory);
  tool(tool$storePlaceOrder);
  tool(tool$storeGetOrderById);
  tool(tool$storeDeleteOrder);
  tool(tool$userCreateUser);
  tool(tool$userCreateUsersWithListInput);
  tool(tool$userLoginUser);
  tool(tool$userLogoutUser);
  tool(tool$userSayRandom);
  tool(tool$userGetUserByName);
  tool(tool$userUpdateUser);
  tool(tool$userDeleteUser);

  return server;
}
