/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, expect, it, test } from "vitest";
import { Petstore } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

it.skip("Pet Pets Store Monday", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step petsStoreMonday.test referencing operation petsStoreMonday not found in document`]",
  );
});

it.skip("Pet My New Test", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step MyNewTest.test referencing operation MyNewTest not found in document`]",
  );
});

test("Pet Find Pets By Status Types", async () => {
  const testHttpClient = createTestHTTPClient("findPetsByStatusTypes");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.pet.findPetsByStatusTypes({});
  expect(result).toBeDefined();
  expect(result).toEqual([
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
        "<value>",
        "<value>",
      ],
    },
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
        "<value>",
      ],
    },
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
      ],
    },
  ]);
});

test("Pet Find Pets By Tags", async () => {
  const testHttpClient = createTestHTTPClient("findPetsByTags");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.pet.findPetsByTags({});
  expect(result).toBeDefined();
  expect(result).toEqual([
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
        "<value>",
        "<value>",
      ],
    },
  ]);
});

test("Pet Get Pet By Ids", async () => {
  const testHttpClient = createTestHTTPClient("getPetByIDS");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.pet.getPetByIDS({
    petId: 137396,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
      "<value>",
      "<value>",
    ],
  });
});

test("Pet Delete Pet", async () => {
  const testHttpClient = createTestHTTPClient("deletePet");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.pet.deletePet({
    petId: 441876,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
});

it.skip("Pet Upload File", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step uploadFile.test referencing operation uploadFile not found in document`]",
  );
});

it.skip("Pet Mcp", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step MCP.test referencing operation MCP not found in document`]",
  );
});

it.skip("Pet Mcp Test", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step MCPTest.test referencing operation MCPTest not found in document`]",
  );
});
