/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, expect, it, test } from "vitest";
import { Petstore } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

it.skip("Store Get Inventory", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step getInventory.test referencing operation getInventory not found in document`]",
  );
});

test("Store Place Order", async () => {
  const testHttpClient = createTestHTTPClient("placeOrder");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.store.placeOrder({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Store Get Order By Id", async () => {
  const testHttpClient = createTestHTTPClient("getOrderById");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.store.getOrderById({
    orderId: 614993,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Store Delete Order", async () => {
  const testHttpClient = createTestHTTPClient("deleteOrder");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.store.deleteOrder({
    orderId: 127902,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});
