/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it } from "vitest";

it.skip("Store Get Inventory", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step getInventory.test referencing operation getInventory not found in document`]",
  );
});

it.skip("Store Place Order", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step placeOrder.test referencing operation placeOrder not found in document`]",
  );
});

it.skip("Store Get Order By Id", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step getOrderById.test referencing operation getOrderById not found in document`]",
  );
});

it.skip("Store Delete Order", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step deleteOrder.test referencing operation deleteOrder not found in document`]",
  );
});
