/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, expect, it, test } from "vitest";
import { Petstore } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

it.skip("User Create User", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step createUser.test referencing operation createUser not found in document`]",
  );
});

it.skip("User Create Users With List Input", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step createUsersWithListInput.test referencing operation createUsersWithListInput not found in document`]",
  );
});

it.skip("User Login User", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step loginUser.test referencing operation loginUser not found in document`]",
  );
});

it.skip("User Logout User", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step logoutUser.test referencing operation logoutUser not found in document`]",
  );
});

test("User Get User By Name", async () => {
  const testHttpClient = createTestHTTPClient("getUserByName");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.user.getUserByName({
    username: "Zachery_Lubowitz15",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    username: "theUser",
    firstName: "John",
    lastName: "James",
    email: "john@email.com",
    password: "12345",
    phone: "12345",
    userStatus: 1,
  });
});

test("User Update User", async () => {
  const testHttpClient = createTestHTTPClient("updateUser");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  await petstore.user.updateUser({
    username: "Dandre_Hand41",
    user: {
      id: 10,
      username: "theUser",
      firstName: "John",
      lastName: "James",
      email: "john@email.com",
      password: "12345",
      phone: "12345",
      userStatus: 1,
    },
  });
});

test("User Delete User", async () => {
  const testHttpClient = createTestHTTPClient("deleteUser");

  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await petstore.user.deleteUser({
    username: "Demetris_Schmitt",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    username: "theUser",
    firstName: "John",
    lastName: "James",
    email: "john@email.com",
    password: "12345",
    phone: "12345",
    userStatus: 1,
  });
});

it.skip("User Say Hello", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step sayHello.test referencing operation sayHello not found in document`]",
  );
});
