/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { planDeletePlan } from "../funcs/planDeletePlan.js";
import { planGetPlanByIDS } from "../funcs/planGetPlanByIDS.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Plan extends ClientSDK {
  /**
   * Find plan by ID
   *
   * @remarks
   * Returns a single plan
   */
  async getPlanByIDS(
    request: operations.GetPlanByIDSRequest,
    options?: RequestOptions,
  ): Promise<components.Pet> {
    return unwrapAsync(planGetPlanByIDS(
      this,
      request,
      options,
    ));
  }

  /**
   * Deletes a plan
   */
  async deletePlan(
    request: operations.DeletePlanRequest,
    options?: RequestOptions,
  ): Promise<components.Pet> {
    return unwrapAsync(planDeletePlan(
      this,
      request,
      options,
    ));
  }
}
