/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productSayNewRandomRandom } from "../funcs/productSayNewRandomRandom.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Product extends ClientSDK {
  /**
   * Say new random random
   *
   * @remarks
   * Returns a new random random message
   */
  async sayNewRandomRandom(
    options?: RequestOptions,
  ): Promise<operations.SayNewRandomRandomResponseBody> {
    return unwrapAsync(productSayNewRandomRandom(
      this,
      options,
    ));
  }
}
