/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { randomGetRandomPet } from "../funcs/randomGetRandomPet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Random extends ClientSDK {
  /**
   * Get a random pet
   *
   * @remarks
   * Returns a random pet
   */
  async getRandomPet(
    options?: RequestOptions,
  ): Promise<components.Pet> {
    return unwrapAsync(randomGetRandomPet(
      this,
      options,
    ));
  }
}
