// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeletePlanRequest struct {
	APIKey *string `header:"style=simple,explode=false,name=api_key"`
	// Plan id to delete
	PlanID int64 `pathParam:"style=simple,explode=false,name=planId"`
}

func (o *DeletePlanRequest) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *DeletePlanRequest) GetPlanID() int64 {
	if o == nil {
		return 0
	}
	return o.PlanID
}

type DeletePlanResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Plan deleted
	Pet *components.Pet
}

func (o *DeletePlanResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeletePlanResponse) GetPet() *components.Pet {
	if o == nil {
		return nil
	}
	return o.Pet
}
