// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type FindPetsByTagsTesterRequest struct {
	// Tags to filter by
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
}

func (o *FindPetsByTagsTesterRequest) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

type FindPetsByTagsTesterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pets []components.Pet
}

func (o *FindPetsByTagsTesterResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *FindPetsByTagsTesterResponse) GetPets() []components.Pet {
	if o == nil {
		return nil
	}
	return o.Pets
}
