// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetPlanByIDSRequest struct {
	// ID of plan to return
	PlanID int64 `pathParam:"style=simple,explode=false,name=planId"`
}

func (o *GetPlanByIDSRequest) GetPlanID() int64 {
	if o == nil {
		return 0
	}
	return o.PlanID
}

type GetPlanByIDSResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pet *components.Pet
}

func (o *GetPlanByIDSResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPlanByIDSResponse) GetPet() *components.Pet {
	if o == nil {
		return nil
	}
	return o.Pet
}
