// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type SayHelloResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	String *string
}

func (o *SayHelloResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SayHelloResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}
