// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// SayHelloResponseBody - successful operation
type SayHelloResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *SayHelloResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SayHelloResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object *SayHelloResponseBody
}

func (o *SayHelloResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SayHelloResponse) GetObject() *SayHelloResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
