// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// SayNewRandomRandomResponseBody - successful operation
type SayNewRandomRandomResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *SayNewRandomRandomResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SayNewRandomRandomResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object *SayNewRandomRandomResponseBody
}

func (o *SayNewRandomRandomResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SayNewRandomRandomResponse) GetObject() *SayNewRandomRandomResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
