// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// SayNewRandomResponseBody - successful operation
type SayNewRandomResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *SayNewRandomResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SayNewRandomResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object *SayNewRandomResponseBody
}

func (o *SayNewRandomResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SayNewRandomResponse) GetObject() *SayNewRandomResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
