// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// SayRandomResponseBody - successful operation
type SayRandomResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *SayRandomResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SayRandomResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object *SayRandomResponseBody
}

func (o *SayRandomResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SayRandomResponse) GetObject() *SayRandomResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
