/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the meep-moop SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx petFindPetsByTags.example.ts
 */

import { Petstore } from "meep-moop";

const petstore = new Petstore({
  apiKey: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await petstore.pet.findPetsByTags({});

  console.log(result);
}

main().catch(console.error);
