/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the meep-moop SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx petPetsStoreMonday.ts
 */

import { Petstore } from "meep-moop";

const petstore = new Petstore({
  apiKey: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await petstore.petsStoreMonday({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value 1>",
      "<value 2>",
    ],
  });

  console.log(result);
}

main().catch(console.error);
