workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.yaml
targets:
    petstore:
        target: typescript
        source: petstore-oas
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-oas-code-samples
            blocking: false
