/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * successful operation
 */
export type SayNewRandomResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const SayNewRandomResponseBody$inboundSchema: z.ZodType<
  SayNewRandomResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type SayNewRandomResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const SayNewRandomResponseBody$outboundSchema: z.ZodType<
  SayNewRandomResponseBody$Outbound,
  z.ZodTypeDef,
  SayNewRandomResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SayNewRandomResponseBody$ {
  /** @deprecated use `SayNewRandomResponseBody$inboundSchema` instead. */
  export const inboundSchema = SayNewRandomResponseBody$inboundSchema;
  /** @deprecated use `SayNewRandomResponseBody$outboundSchema` instead. */
  export const outboundSchema = SayNewRandomResponseBody$outboundSchema;
  /** @deprecated use `SayNewRandomResponseBody$Outbound` instead. */
  export type Outbound = SayNewRandomResponseBody$Outbound;
}

export function sayNewRandomResponseBodyToJSON(
  sayNewRandomResponseBody: SayNewRandomResponseBody,
): string {
  return JSON.stringify(
    SayNewRandomResponseBody$outboundSchema.parse(sayNewRandomResponseBody),
  );
}

export function sayNewRandomResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SayNewRandomResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SayNewRandomResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SayNewRandomResponseBody' from JSON`,
  );
}
